cf-cli_6.53.0_linux_x86-64.tgz:
  size: 8973024
  object_id: d52bfb69-0e5c-4b55-7879-b2d17796f7b5
  sha: 48a3def0c9741a1b454bf73ded2a229a13bdfb2e
cf7-cli_7.6.0_linux_x86-64.tgz:
  size: 7405404
  object_id: f2427207-7f19-4993-6247-8ba78bb92ff2
  sha: 3edae4ef54ac3b1691cf4d07a7400ec2ce7751b0
cf8-cli_8.6.1_linux_x86-64.tgz:
  size: 8831474
  object_id: e6e4149b-053f-4c49-7591-05d7ddcde3ea
  sha: 8f49e16ac252066a029de1624b9bf59f3dde781a
