cf-cli_6.53.0_linux_x86-64.tgz:
  size: 8973024
  object_id: 487ecf2b-7ff4-4a43-409f-4ac64277b95e
  sha: 48a3def0c9741a1b454bf73ded2a229a13bdfb2e
cf7-cli_7.4.0_linux_x86-64.tgz:
  size: 7882979
  object_id: dea96ec1-e199-46ce-4d21-c93d36a139f2
  sha: 39dbb657dd3f4be5078e1b556da19b329588dae4
cf8-cli_8.1.0_linux_x86-64.tgz:
  size: 8840669
  object_id: 242cc2ed-0298-4374-6dde-b4fe25792a8e
  sha: 48b889d07af6201811d0d6760cc5a3b13f49b84d
